### ISSUE TITLE
Link autocomplete field conflicts

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/select2#10]
The CKEditor link dialog doesn't work correctly with Select2 enabled.

**Comment by laryn** [comment]
Adding `edit-attributes-href` in the `IDs` for Exclusion Rules is a workaround, but it seems to also disable autocomplete on that field.

**Comment by laryn** [comment]
This issue seems to be present on all "link autocomplete" fields including CKEditor link dialog (although autocomplete fields like taxonomy term tags seem to work fine). Disabling `select2` for autocomplete seems to be necessary until this is resolved.
![Screen Shot 2020-06-11 at 11 35 47 AM](https://user-images.githubusercontent.com/871421/84414984-bd45ad80-abd7-11ea-8e59-79cedfb910fd.jpg)

Maybe this PR can help identify a way to exclude Select2 from these 'link autocomplete' fields:
https://github.com/backdrop/backdrop/pull/3066/files

**Comment by herbdool** [comment]
Got bit by this too. Thanks for the temporary fix.

**Comment by laryn** [comment]
@herbdool Are you able to test https://github.com/backdrop-contrib/select2/commit/925752c759b98632643894cff87592dfe629f383 ?

**Comment by yorkshire-pudding** [comment]
I seem to be getting this problem in the CKeditor link button. The element for the link is:
```html
<input type="text" id="edit-attributes-href--2" name="attributes[href]" value="" size="60" maxlength="256" placeholder=" " class="form-text form-autocomplete" autocomplete="OFF" aria-autocomplete="list">
```

<details>
<summary>Console Log</Summary>

```
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
Backdrop.select2.js?v=1.x-1.0:312 Uncaught TypeError: Cannot read properties of undefined (reading 'by_selectors')
    at Backdrop.Select2.markExcludedElements (Backdrop.select2.js?v=1.x-1.0:312:45)
    at Backdrop.Select2.processElements (Backdrop.select2.js?v=1.x-1.0:300:10)
    at Backdrop.Select2.setContext (Backdrop.select2.js?v=1.x-1.0:296:10)
    at Object.<anonymous> (Backdrop.select2.js?v=1.x-1.0:647:37)
    at i (jquery.js?v=1.12.4:2:27449)
    at Object.fireWith [as resolveWith] (jquery.js?v=1.12.4:2:28213)
    at y (jquery.js?v=1.12.4:4:22723)
    at XMLHttpRequest.c (jquery.js?v=1.12.4:4:26927)
Backdrop.Select2.markExcludedElements @ Backdrop.select2.js?v=1.x-1.0:312
Backdrop.Select2.processElements @ Backdrop.select2.js?v=1.x-1.0:300
Backdrop.Select2.setContext @ Backdrop.select2.js?v=1.x-1.0:296
(anonymous) @ Backdrop.select2.js?v=1.x-1.0:647
i @ jquery.js?v=1.12.4:2
fireWith @ jquery.js?v=1.12.4:2
y @ jquery.js?v=1.12.4:4
c @ jquery.js?v=1.12.4:4
XMLHttpRequest.send (async)
send @ jquery.js?v=1.12.4:4
ajax @ jquery.js?v=1.12.4:4
attach @ Backdrop.select2.js?v=1.x-1.0:632
(anonymous) @ backdrop.js?v=1.24.2:73
each @ jquery.js?v=1.12.4:2
Backdrop.attachBehaviors @ backdrop.js?v=1.24.2:71
(anonymous) @ backdrop.js?v=1.24.2:699
i @ jquery.js?v=1.12.4:2
fireWith @ jquery.js?v=1.12.4:2
ready @ jquery.js?v=1.12.4:2
K @ jquery.js?v=1.12.4:2
```

</details>

I've tried adding the ID to exclusions, the node edit/add paths to exclusion but I actually have to disable both ' Use for all <select> elements on admin pages' and 'Use Select2 for elements with autocomplete (e.g. Tags)' for it to work.

**Comment by yorkshire-pudding** [comment]
Seems to be working.
