### ISSUE TITLE
Config cannot be imported

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/select2#18]
**Steps to reproduce**

1. Export config from an environment with select2 enabled and configured
2. Attempt to import into another environment with select2 enabled

**Expected result**
Config is imported

**Actual result**
The configuration "select2.settings" is not owned by any module. Try enabling the module that provides this configuration, then importing again.

**Comment by yorkshire-pudding** [comment]
@laryn please see issue above and attached pull request.

**Comment by laryn** [comment]
Thanks @yorkshire-pudding -- looks good!
