### ISSUE TITLE
Maintainer request

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/select2#8]
This module looks abandoned. I'd like to try to get it running since the [core issue](https://github.com/backdrop/backdrop-issues/issues/3069) is pretty stale.

Since there is no maintainer, I'm applying for maintainership to see if I can get this working.

**Comment by klonos** [comment]
Hello @laryn 👋 ...according to https://github.com/backdrop-ops/contrib#backdrop-contributed-project-agreement we need to give the maintainer of the project 2 weeks time to respond, but I'm happy to expedite things in this case, provided at least another member of the Contrib Squad agrees to this. Reasons being:

- given that the specific user has not given any signs of activity
- the fact that https://github.com/gifad 404's

**Comment by klonos** [comment]
...pinging @jenlampton and/or @herbdool ^^ 😉

**Comment by herbdool** [comment]
Go ahead @laryn

**Comment by laryn** [comment]
Thanks!
